version: '3.8'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks: 
      - desafio-nginx-network
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s
    command: node index.js
    restart: always
    networks:
      - desafio-nginx-network
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always 
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-nginx-network
networks:
  desafio-nginx-network:
    driver: bridge
